services:
  nginx-site:
    build:
      context: ./nginx-site
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    restart: always
